---
# tasks file for keycloak

- name: Add extension to Wildfly's configuration file
  lineinfile:
    dest: "{{ wildfly_standalone_config_path }}"
    insertbefore: </extensions>
    line: "{{ keycloak_ext }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750
  notify:
    - restart wildfly
    - change standalone data mode

- name: Add subsytem to Wildfly's configuration file
  lineinfile:
    dest: "{{ wildfly_standalone_config_path }}"
    insertbefore: </profile>
    line: "{{ keycloak_subsystem }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750
  notify:
    - restart wildfly
    - change standalone data mode

- name: Add cache container
  lineinfile:
    dest: "{{ wildfly_standalone_config_path }}"
    insertafter: '<subsystem xmlns="urn:jboss:domain:infinispan:3.0">'
    line: "{{ keycloak_cache_container }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750
  notify:
    - restart wildfly
    - change standalone data mode

- name: Add default datasource
  lineinfile:
    dest: "{{ wildfly_standalone_config_path }}"
    insertbefore: </datasources>
    line: "{{ keycloak_default_ds }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750
  when: keycloak_custom_ds == ""
  notify:
    - restart wildfly
    - change standalone data mode

- name: Delete keycloak tar file
  file: path={{ keycloak_download_dir }}/{{ keycloak_download_file }}
        state=absent
  when: not keycloak_installation.stat.exists
