---
# tasks file for keycloak

- name: Create driver directory
  file:
    path: "{{ keycloak_ds_driver_path }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750
    recurse: yes
    state: directory

- name: Download driver
  get_url:
    url: "{{ keycloak_ds_driver_url }}"
    dest: "{{ keycloak_ds_driver_path }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750

- name: Copy module.xml
  template:
    src: module.xml.j2
    dest: "{{ keycloak_ds_driver_path }}/module.xml"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750
  notify:
    - restart wildfly
    - change standalone data mode

- name: Add driver to Wildfly's configuration file
  lineinfile:
    dest: "{{ wildfly_standalone_config_path }}"
    insertbefore: </drivers>
    line: "{{ keycloak_custom_driver }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750
  notify:
    - restart wildfly
    - change standalone data mode
