---
# tasks file for keycloak

# This task will FAIL if an admin user already exists. Check the README file
# for more information.
- name: Create management user
  command: >
    {{ wildfly_dir }}/bin/add-user-keycloak.sh -r master
    -u {{ keycloak_management_user }} -p {{ keycloak_management_password }}
  become_user: "{{ wildfly_user }}"
  when: keycloak_management_user is defined and
        keycloak_management_password is defined
  notify: restart wildfly
